plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\andre\\Desktop\\Git Projects\\real-moments\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\andre\\Desktop\\Git Projects\\real-moments"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]